import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ScrollToTopButton from "@/components/ui/ScrollToTopButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Nihon Automação",
  description: "Generated by create next app",
};

import HeaderToggle from "@/components/layout/HeaderToggle";
import FooterToggle from "@/components/layout/FooterToggle";

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt-BR">
    <body className="flex flex-col min-h-screen bg-white">
      {/* Header fixo (escondido em /admin via HeaderToggle) */}
      <HeaderToggle />

      {/* Conteúdo rolável */}
      <main className="bg-white">
        {children}
      </main>

      {/* Footer (escondido em /admin via FooterToggle) */}
      <FooterToggle />
      <ScrollToTopButton />
    </body>
    </html>
  );
}
