import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import ScrollToTopButton from "@/components/ui/ScrollToTopButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Nihon Automação",
  description: "Generated by create next app",
};

import Footer from "@/components/layout/Footer";
import Header from "@/components/layout/Header";

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt-BR">
  <body className="flex flex-col min-h-screen bg-white">
    {/* Header fixo */}
    <Header />

    {/* Conteúdo rolável */}
    <main className="bg-white">
      {children}
    </main>

    {/* Footer */}
    <Footer />
    <ScrollToTopButton />
  </body>
    </html>
  );
}
